### PR TITLE
Option to ensure unique results

### PR DESCRIPTION
**Pull request by gezalore**
I have seen that his has come up before, but I have made a few patches to enable the plugin to return unique search results even if HIST_IGNORE_ALL_DUPS is not set.

There are good reasons why the user would not want to set HIST_IGNORE_ALL_DUPS. I for one like to be able to see my precise history. Also for plugins like zsh-autosuggestions, it is helpful to be able to analyse the history context when generating suggestions, which would be hopeless if older duplicate entries were later removed.

The implementation uses lazy evaluation to compute the next unique result only when it is required, so the response time is still snappy. It also observes HIST_IGNORE_ALL_DUPS and if it is set it does no further processing, so if you are using that option you should perceive no change.

Would you be interested in merging this?

Thanks,
Geza

### CODE REVIEW

**Comment by sunaku** [comment]
Thanks @gezalore! :+1: Hey @guidovansteen, @sorin-ionescu, @vguerci could you help review this PR?

**Comment by gezalore** [comment]
Just a gentle ping to see if you haveany feedback?

**Comment by guidovansteen** [comment]
Hi Geza Lore, 

Thanks a lot for your work. I am sorry for not replying earlier (busy with other things). 
I like your "ensure unique" contribution. I have tested it (not very thorougly). It seems to work fine. 

I only have only two comments: 

1) Why is HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE unset at the beginning the script. I think this is not necessary. If the variable is not explicitly created, it will not exist anyway. If the variable is automatically unset, it has to be set again each time when they start a new shell. This might be confusing. So please remove the unsetting, unless I missed something. 

2) All variable names in the script are prepended with "_history_substring_search". I think you should also apply this coding style to "escaped_query". So, please call it "_history_substring_search_escaped_query" (or "_history_substring_search_query_escaped", which is the current variable name). 

Best wishes, 

Guido van Steen

**Comment by sunaku** [comment]
On a side note, I've been using this PR branch for a week and haven't found any issues so far. :+1: 

@gezalore if you apply @guidovansteen's suggestions, I think we can merge this PR, thanks!

**Comment by gezalore** [comment]
Hi Guido van Steen,

Thank you for the comments, I also apologise for the long delay in the reply, I have been busy as well recently.

I will try to address your concerns:

1) The reason HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE is unset at the very beginning is twofold. Partly it is documentation, so the "configuration variables" section lists all available variables that the user could tweak, though I give it to you, given how short the manual is this is not currently a big concern. The other reason it is unset at the beginning is that all other configuration variables are assigned a default value at the beginning of the script, even if they are already defined, so this should not be different either, unsetting it is simply the act of assigning default state. This way the state is fully known after sourcing the script, and can be customized in your zshrc afterwards, which will set the variable automatically when you open a new shell.

2) In the current script, only global variables are prefixed with "_history_substring_search". For locals this is not necessary as they do not pollute the global namespace. 'escaped_query' is a local variable, and is uses once in the statement following its declaration, and because it is is local, it will disappear when the containing function returns. There are already a handful of locals in the script, none of which are using a prefix, so I believe the current style is consistent with the rest of the code.

What is your opinion with these thoughts in mind?

Kind Regards,
Geza Lore

**Comment by guidovansteen** [comment]
Hi Geza Lore,

1) I appreciate the reasons why you unset a global flag. However, unsetting
it remains different from the way global flags are handled in the rest of
the script. This is simply because in the current script global flags are
NOT unset. As you write, global flags are currently given a default value,
which may be changed later on. Therefore, I really insist on giving
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE a default value as well, instead of
an unset default state.

2) In the original script the prefix "_history_substring_search" was used
for each variable. You are right that the current code does not
consistently adhere to this practice anymore. So, this is a minor point to
me. As far as I am concerned you may use the new name "escaped_query"
(although your patch changed the original name
"_history_substring_search_query_escaped" into escaped_query).

Thank you for your work!

Kind regards,

Guido van Steen

**Comment by gezalore** [comment]
Ok, just pushed a proposed fix, which sets the variable to the empty string instead of unsetting it. The net result is the same, except that now you will always have the name in your shell after sourcing the script.

Bests,
Geza

**Comment by sunaku** [comment]
Hi Geza,

I found an issue with `HIST_FIND_NO_DUPS` in this pull request:

```sh
?remotes/gezalore/ensure_unique ~/.zsh/bundle/2/zsh-history-substring-search> zsh -f
yantram% bindkey '^[[A' history-substring-search-up
yantram% bindkey '^[[B' history-substring-search-down
yantram% setopt HIST_FIND_NO_DUPS
yantram% source zsh-history-substring-search.zsh
yantram% echo hello
hello
yantram% date
Mon May 23 10:54:31 PDT 2016
yantram% echo world
world
yantram% echo hello  # <=== pressing UP skipped "echo world" and went to "echo hello"
```

The search is unnecessarily repeated, producing the wrong result.

Cheers.

**Comment by gezalore** [comment]
Hi Suraj,

Very interesting, that is actually an issue on master as well. Here is how I reproduced it:

```
zsh -f
% source zsh-history-substring-search.zsh
% bindkey '^[[A' history-substring-search-up
% bindkey '^[[B' history-substring-search-down
% setopt HIST_FIND_NO_DUPS
% echo hello
hello
% date
Mon May 23 21:45:12 BST 2016
% echo world
world
% echo # Now press up. It completes to 'echo world'. Do not execute, hit C-c to clear
% echo # Now press up. It completes to 'echo hello'. Do not execute, hit C-c to clear
% echo # Now press up. It completes to 'echo world'. Repeat..
```

Anyhow, I just pushed a fix, could you confirm it fixes your case as well.

Thanks!

**Comment by sunaku** [comment]
:+1: Looks good, thanks @gezalore.

**Comment by sunaku** [comment]
@guidovansteen please merge this when you're ready. :shipit:

**Comment by gezalore** [comment]
Another gentle ping, please?

**Comment by sunaku** [comment]
Merged! :+1: Thanks @gezalore! :sparkling_heart:

**Pull request merged**
