### PR TITLE
Fix breakage with setopt ERR_RETURN (Issue #60)

### LINKED ISSUE #60: setopt ERR_RETURN breaks this plugin
I updated my plugin and it mostly stopped working. I suspect the re-factorings @gazalore because that's the biggest changeset. At least always when I search for something like "git push<UP>" I get any kinds of git commands and not only the "git push" commands as I expect.

For my own sanity, I forked this repo so new sudden changes doesn't disrupt me as easily again. In that repo I reverted to a version which seem to work. https://github.com/Tarrasch/zsh-history-substring-search

I apologize for not providing more details, but time will tell if others will report similar issues already or not.

### PR DESCRIPTION
**Pull request by gezalore**
Hi @sunaku, 

I believe this should fix #60.
@Tarrasch could you check if the fix is working for you?

Thanks,
Geza

### CODE REVIEW

**Comment by gezalore** [comment]
@mindeunix might like to check the fix as well.

**Comment by mindeunix** [comment]
Thanks @gezalore, I can confirm it works for me

**Comment by sunaku** [comment]
Thanks for the PR! :+1: The issue being fixed is a strange one: why would those increment and decrement operations fail in the first place?  Because the variable they're operating on is not yet defined?  If so, wouldn't a cleaner fix be to initialize those variables to zero?

**Comment by gezalore** [comment]
Whenever the expression in the (( )) evaluates to 0, it is considered a 'failed' command. Have a play:
```
$ typeset -i x=0
$ (( x++ )) && echo "YAY" || echo "BOO"; echo $x
$ (( x++ )) && echo "YAY" || echo "BOO"; echo $x
$ (( x-- )) && echo "YAY" || echo "BOO"; echo $x
$ (( x-- )) && echo "YAY" || echo "BOO"; echo $x
```

**Comment by sunaku** [comment]
Thanks @gezalore.  Then I would prefer the more verbose POSIX syntax `x=$(( x + 1 ))`  because that way people won't be surprised by the `|| true` workaround which stands apart from all of the surrounding code.  It's a trade-off: self-documenting but more verbose code versus surprising but succinct code that requires a comment to explain it.  What do you think?

**Comment by gezalore** [comment]
I think `x=$(( x + 1 ))` is unclear if the actual 'x' identifier is 25 characters long, `x+=1` might work.

**Comment by sunaku** [comment]
Good point @gezalore. :+1:  Please update this PR to use `+= 1` and we'll merge it.

**Comment by gezalore** [comment]
Thanks @sunaku, done. Note that `-=` is only valid in a `let` statement which has the same issue with the 0 result, so had to use `+=-1` to replace the `--`.

**Pull request merged**
